/**
 * Backup Automation Service
 *
 * Creates point-in-time snapshots of the workbench database using
 * libSQL VACUUM INTO. Stores backup metadata in a dedicated `backups`
 * table so listing and verification never touch the filesystem.
 *
 * Backup files live under .nexus/backups/ (local dev) or /tmp/.nexus/backups/
 * (Vercel serverless). Each backup is a fully self-contained SQLite file.
 */

import { access, mkdir, stat, copyFile } from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { getLibsqlClient, sqlAll, sqlGet, sqlRun, sqlBatch } from "../libsqlDb";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface BackupResult {
  id: string;
  timestamp: number;
  sizeBytes: number;
  tables: Record<string, number>;
}

export interface BackupInfo {
  id: string;
  timestamp: number;
  sizeBytes: number;
  tableCounts: Record<string, number>;
  status: "completed" | "failed" | "restoring";
}

export interface RestoreResult {
  id: string;
  restoredFrom: string;
  timestamp: number;
  tables: Record<string, number>;
}

export interface VerifyResult {
  id: string;
  valid: boolean;
  checks: {
    fileExists: boolean;
    sizeMatch: boolean;
    tableCountsMatch: boolean;
    integrityOk: boolean;
  };
  details?: string;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const VALID_TABLE_NAMES = new Set([
  "actors",
  "projects",
  "project_members",
  "project_state",
  "project_run_artifact_index",
  "experiment_records",
  "sync_audit",
  "project_history",
  "canonical_state",
  "backups",
]);

function resolveBackupDir(): string {
  const base = process.env.VERCEL ? "/tmp/.nexus" : path.join(process.cwd(), ".nexus");
  return path.join(base, "backups");
}

function backupFilePath(backupId: string): string {
  return path.join(resolveBackupDir(), `${backupId}.db`);
}

function now(): number {
  return Date.now();
}

// ─── Schema ───────────────────────────────────────────────────────────────────

let schemaReady = false;

async function ensureBackupSchema(): Promise<void> {
  if (schemaReady) return;

  await sqlBatch([
    {
      sql: `
        CREATE TABLE IF NOT EXISTS backups (
          id TEXT PRIMARY KEY,
          timestamp INTEGER NOT NULL,
          size_bytes INTEGER NOT NULL,
          table_counts TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'completed'
        )
      `,
    },
  ]);

  schemaReady = true;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Count rows in each known table. Returns a map of table name -> row count.
 */
async function countTableRows(): Promise<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const table of VALID_TABLE_NAMES) {
    if (table === "backups") continue; // skip self
    try {
      const row = await sqlGet(`SELECT COUNT(*) as count FROM ${table}`);
      counts[table] = (row?.count as number) ?? 0;
    } catch {
      // Table may not exist yet
      counts[table] = 0;
    }
  }
  return counts;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Create a point-in-time backup of the workbench database.
 *
 * Uses libSQL VACUUM INTO to produce a compact, self-contained copy.
 * Records metadata (size, table row counts, timestamp) in the backups table.
 */
export async function createBackup(): Promise<BackupResult> {
  await ensureBackupSchema();

  const backupId = crypto.randomUUID();
  const backupDir = resolveBackupDir();
  const filePath = backupFilePath(backupId);
  const timestamp = now();

  // Ensure backup directory exists
  await mkdir(backupDir, { recursive: true });

  // Capture table counts before backup
  const tables = await countTableRows();

  // Execute VACUUM INTO — produces a standalone SQLite file
  const client = getLibsqlClient();

  // VACUUM INTO requires the path to be a string literal (not parameterized).
  // The backupId is a UUID generated by crypto.randomUUID(), so it is safe.
  const escapedPath = filePath.replace(/'/g, "''");
  await client.execute(`VACUUM INTO '${escapedPath}'`);

  // Read the resulting file size
  let sizeBytes: number;
  try {
    const fileStat = await stat(filePath);
    sizeBytes = fileStat.size;
  } catch {
    // If file wasn't created, mark as failed
    await sqlRun(`INSERT INTO backups (id, timestamp, size_bytes, table_counts, status) VALUES (?, ?, ?, ?, ?)`, [
      backupId,
      timestamp,
      0,
      JSON.stringify(tables),
      "failed",
    ]);
    throw new Error(`Backup file was not created at ${filePath}`);
  }

  // Record metadata
  await sqlRun(`INSERT INTO backups (id, timestamp, size_bytes, table_counts, status) VALUES (?, ?, ?, ?, ?)`, [
    backupId,
    timestamp,
    sizeBytes,
    JSON.stringify(tables),
    "completed",
  ]);

  return { id: backupId, timestamp, sizeBytes, tables };
}

/**
 * List all recorded backups, most recent first.
 */
export async function listBackups(): Promise<BackupInfo[]> {
  await ensureBackupSchema();

  const rows = await sqlAll(
    `SELECT id, timestamp, size_bytes, table_counts, status FROM backups ORDER BY timestamp DESC`,
  );

  return rows.map((row) => ({
    id: row.id as string,
    timestamp: row.timestamp as number,
    sizeBytes: row.size_bytes as number,
    tableCounts: JSON.parse(row.table_counts as string) as Record<string, number>,
    status: row.status as BackupInfo["status"],
  }));
}

/**
 * Restore the workbench database from a backup snapshot.
 *
 * 1. Verifies the backup file exists.
 * 2. Copies the backup file over the current workbench database.
 * 3. Records the restore event.
 */
export async function restoreBackup(backupId: string): Promise<RestoreResult> {
  await ensureBackupSchema();

  // Look up backup metadata
  const backup = await sqlGet(`SELECT id, timestamp, size_bytes, table_counts, status FROM backups WHERE id = ?`, [
    backupId,
  ]);

  if (!backup) {
    throw new Error(`Backup not found: ${backupId}`);
  }

  if (backup.status === "failed") {
    throw new Error(`Cannot restore a failed backup: ${backupId}`);
  }

  const filePath = backupFilePath(backupId);

  // Verify the backup file exists
  try {
    await access(filePath);
  } catch {
    throw new Error(`Backup file not found on disk: ${filePath}`);
  }

  // Determine target database path
  const dbPath = process.env.VERCEL ? "/tmp/.nexus/workbench.db" : path.join(process.cwd(), ".nexus", "workbench.db");

  // Copy backup over the current database
  await copyFile(filePath, dbPath);

  const restoredFrom = backupId;
  const timestamp = now();

  // Read table counts from the restored database
  const tables = await countTableRows();

  // Record the restore event
  await sqlRun(`INSERT INTO backups (id, timestamp, size_bytes, table_counts, status) VALUES (?, ?, ?, ?, ?)`, [
    `restore-${backupId}`,
    timestamp,
    (backup.size_bytes as number) ?? 0,
    JSON.stringify(tables),
    "completed",
  ]);

  return { id: `restore-${backupId}`, restoredFrom, timestamp, tables };
}

/**
 * Verify the integrity of a backup.
 *
 * Checks:
 * 1. File exists on disk
 * 2. File size matches recorded size
 * 3. Table counts match (by opening the backup as a separate database)
 * 4. SQLite integrity check passes
 */
export async function verifyBackup(backupId: string): Promise<VerifyResult> {
  await ensureBackupSchema();

  const backup = await sqlGet(`SELECT id, timestamp, size_bytes, table_counts, status FROM backups WHERE id = ?`, [
    backupId,
  ]);

  if (!backup) {
    throw new Error(`Backup not found: ${backupId}`);
  }

  const filePath = backupFilePath(backupId);
  const checks = {
    fileExists: false,
    sizeMatch: false,
    tableCountsMatch: false,
    integrityOk: false,
  };

  // Check 1: File exists
  try {
    await access(filePath);
    checks.fileExists = true;
  } catch {
    return {
      id: backupId,
      valid: false,
      checks,
      details: "Backup file not found on disk",
    };
  }

  // Check 2: Size matches
  try {
    const fileStat = await stat(filePath);
    checks.sizeMatch = fileStat.size === (backup.size_bytes as number);
  } catch {
    return {
      id: backupId,
      valid: false,
      checks,
      details: "Could not read backup file stats",
    };
  }

  // Check 3: Table counts match
  // Open the backup file as a separate libsql database and count rows
  try {
    const { createClient } = await import("@libsql/client");
    const backupClient = createClient({ url: `file:${filePath}` });

    const recordedCounts = JSON.parse(backup.table_counts as string) as Record<string, number>;
    const currentCounts: Record<string, number> = {};

    for (const table of Object.keys(recordedCounts)) {
      try {
        const result = await backupClient.execute(`SELECT COUNT(*) as count FROM ${table}`);
        currentCounts[table] = (result.rows[0]?.count as number) ?? 0;
      } catch {
        currentCounts[table] = 0;
      }
    }

    backupClient.close();

    checks.tableCountsMatch =
      JSON.stringify(recordedCounts, Object.keys(recordedCounts).sort()) ===
      JSON.stringify(currentCounts, Object.keys(currentCounts).sort());
  } catch {
    // If we can't open the backup file, table count check fails
    checks.tableCountsMatch = false;
  }

  // Check 4: SQLite integrity check
  try {
    const { createClient } = await import("@libsql/client");
    const backupClient = createClient({ url: `file:${filePath}` });

    const result = await backupClient.execute("PRAGMA integrity_check");
    const firstRow = result.rows[0];
    checks.integrityOk = firstRow?.integrity_check === "ok" || firstRow?.[0] === "ok";

    backupClient.close();
  } catch {
    checks.integrityOk = false;
  }

  const valid = checks.fileExists && checks.sizeMatch && checks.tableCountsMatch && checks.integrityOk;

  return {
    id: backupId,
    valid,
    checks,
    details: valid
      ? "All checks passed"
      : `Failed checks: ${Object.entries(checks)
          .filter(([, v]) => !v)
          .map(([k]) => k)
          .join(", ")}`,
  };
}
