/**
 * SBOL 3.0 Serializer — converts Nexus-Bio genetic circuit JSON into
 * validated SBOL 3.0 RDF/XML and Turtle representations.
 *
 * Biological constraints:
 * - Every Component gets an SO (Sequence Ontology) Role per SBOL 3.0 spec
 * - Promoter → SO:0000167, RBS → SO:0000139, CDS → SO:0000316, Terminator → SO:0000141
 * - Interactions use SBO (Systems Biology Ontology) terms
 * - Namespace follows SBOL 3.0 convention: <namespace>/ComponentDefinition/<displayId>
 *
 * Reference: SBOL 3.0 specification (https://sbolstandard.org/docs/SBOL3.0specification)
 */

import type {
  GeneticPart,
  GeneticPartType,
  CircuitNode,
  SBOLComponent,
  SBOLDocument,
  SBOLInteraction,
  SBOLRole,
} from '../types';

// ── SO Role mapping ───────────────────────────────────────────────────────────
const ROLE_MAP: Record<GeneticPartType, SBOLRole> = {
  promoter:   'SO:0000167',
  rbs:        'SO:0000139',
  cds:        'SO:0000316',
  terminator: 'SO:0000141',
};

const ROLE_LABEL: Record<SBOLRole, string> = {
  'SO:0000167': 'Promoter',
  'SO:0000139': 'RBS',
  'SO:0000316': 'CDS',
  'SO:0000141': 'Terminator',
  'SO:0000110': 'Sequence Feature',
  'SO:0000296': 'Origin of Replication',
  'SO:0000057': 'Operator',
};

const SO_URI_PREFIX = 'http://identifiers.org/SO:';
const SBO_URI_PREFIX = 'http://identifiers.org/biomodels.sbo/';

// ── UUID generator (browser-safe, no crypto dependency) ───────────────────────
function generateUUID(): string {
  const hex = '0123456789abcdef';
  let uuid = '';
  for (let i = 0; i < 36; i++) {
    if (i === 8 || i === 13 || i === 18 || i === 23) uuid += '-';
    else if (i === 14) uuid += '4';
    else if (i === 19) uuid += hex[(Math.random() * 4 | 0) + 8];
    else uuid += hex[Math.random() * 16 | 0];
  }
  return uuid;
}

// ── Convert GeneticPart[] to SBOLComponent[] ──────────────────────────────────
function partsToComponents(
  parts: GeneticPart[],
  namespace: string,
): SBOLComponent[] {
  return parts.map(part => ({
    displayId: part.id,
    name: part.label ?? part.id,
    role: ROLE_MAP[part.type] ?? 'SO:0000110',
    sequence: undefined,
    description: `${ROLE_LABEL[ROLE_MAP[part.type]]} with ${
      part.strength !== undefined ? `strength ${part.strength.toFixed(2)}` : 'default strength'
    }`,
    namespace,
  }));
}

// ── Infer interactions from circuit topology ──────────────────────────────────
function inferInteractions(
  nodes: CircuitNode[],
  namespace: string,
): SBOLInteraction[] {
  const interactions: SBOLInteraction[] = [];

  for (const node of nodes) {
    const promoters = node.parts.filter(p => p.type === 'promoter');
    const cdsParts  = node.parts.filter(p => p.type === 'cds');

    // Promoter → CDS = Genetic Production (SBO:0000589)
    for (const pr of promoters) {
      for (const cds of cdsParts) {
        interactions.push({
          displayId: `${namespace}_interaction_${pr.id}_${cds.id}`,
          type: 'SBO:0000589',
          participantIds: [pr.id, cds.id],
        });
      }
    }
  }

  return interactions;
}

// ── Escape XML special characters ─────────────────────────────────────────────
function escXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// ── Serialize to SBOL 3.0 RDF/XML ────────────────────────────────────────────
function serializeToXml(
  doc: Omit<SBOLDocument, 'serializedXml' | 'serializedTurtle'>,
): string {
  const ns = escXml(doc.namespace);
  const lines: string[] = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<rdf:RDF`,
    `  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"`,
    `  xmlns:sbol="http://sbols.org/v3#"`,
    `  xmlns:dcterms="http://purl.org/dc/terms/"`,
    `  xmlns:prov="http://www.w3.org/ns/prov#"`,
    `  xmlns:om="http://www.ontology-of-units-of-measure.org/resource/om-2/"`,
    `  xmlns:SO="http://identifiers.org/SO:"`,
    `  xmlns:SBO="http://identifiers.org/biomodels.sbo/">`,
    ``,
    `  <!-- SBOL 3.0 Document: ${escXml(doc.name)} -->`,
    `  <!-- Generated by Nexus-Bio Axon SBOL Serializer -->`,
    `  <!-- Timestamp: ${doc.createdAt} -->`,
    ``,
  ];

  // Top-level Component (the construct)
  lines.push(`  <sbol:Component rdf:about="${ns}/${escXml(doc.displayId)}">`);
  lines.push(`    <sbol:displayId>${escXml(doc.displayId)}</sbol:displayId>`);
  lines.push(`    <sbol:name>${escXml(doc.name)}</sbol:name>`);
  lines.push(`    <dcterms:description>${escXml(doc.description)}</dcterms:description>`);
  lines.push(`    <sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"/>`);
  lines.push(`    <sbol:role rdf:resource="${SO_URI_PREFIX}0000804"/><!-- Engineered Region -->`);

  // SubComponents
  for (const comp of doc.components) {
    lines.push(`    <sbol:hasFeature>`);
    lines.push(`      <sbol:SubComponent rdf:about="${ns}/${escXml(doc.displayId)}/SubComponent_${escXml(comp.displayId)}">`);
    lines.push(`        <sbol:displayId>SubComponent_${escXml(comp.displayId)}</sbol:displayId>`);
    lines.push(`        <sbol:instanceOf rdf:resource="${ns}/${escXml(comp.displayId)}"/>`);
    lines.push(`      </sbol:SubComponent>`);
    lines.push(`    </sbol:hasFeature>`);
  }

  // Constraints (ordering: i must precede i+1)
  for (let i = 0; i < doc.components.length - 1; i++) {
    const subj = doc.components[i];
    const obj  = doc.components[i + 1];
    lines.push(`    <sbol:hasConstraint>`);
    lines.push(`      <sbol:Constraint rdf:about="${ns}/${escXml(doc.displayId)}/Constraint_${i}">`);
    lines.push(`        <sbol:restriction rdf:resource="http://sbols.org/v3#precedes"/>`);
    lines.push(`        <sbol:subject rdf:resource="${ns}/${escXml(doc.displayId)}/SubComponent_${escXml(subj.displayId)}"/>`);
    lines.push(`        <sbol:object rdf:resource="${ns}/${escXml(doc.displayId)}/SubComponent_${escXml(obj.displayId)}"/>`);
    lines.push(`      </sbol:Constraint>`);
    lines.push(`    </sbol:hasConstraint>`);
  }

  // Interactions
  for (const inter of doc.interactions) {
    lines.push(`    <sbol:hasInteraction>`);
    lines.push(`      <sbol:Interaction rdf:about="${ns}/${escXml(doc.displayId)}/${escXml(inter.displayId)}">`);
    lines.push(`        <sbol:displayId>${escXml(inter.displayId)}</sbol:displayId>`);
    lines.push(`        <sbol:type rdf:resource="${SBO_URI_PREFIX}${inter.type.replace('SBO:', '')}"/>`);
    for (const pid of inter.participantIds) {
      lines.push(`        <sbol:hasParticipation>`);
      lines.push(`          <sbol:Participation>`);
      lines.push(`            <sbol:participant rdf:resource="${ns}/${escXml(doc.displayId)}/SubComponent_${escXml(pid)}"/>`);
      lines.push(`          </sbol:Participation>`);
      lines.push(`        </sbol:hasParticipation>`);
    }
    lines.push(`      </sbol:Interaction>`);
    lines.push(`    </sbol:hasInteraction>`);
  }

  lines.push(`  </sbol:Component>`);
  lines.push(``);

  // Individual Component definitions
  for (const comp of doc.components) {
    lines.push(`  <sbol:Component rdf:about="${ns}/${escXml(comp.displayId)}">`);
    lines.push(`    <sbol:displayId>${escXml(comp.displayId)}</sbol:displayId>`);
    lines.push(`    <sbol:name>${escXml(comp.name)}</sbol:name>`);
    lines.push(`    <dcterms:description>${escXml(comp.description ?? '')}</dcterms:description>`);
    lines.push(`    <sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"/>`);
    lines.push(`    <sbol:role rdf:resource="${SO_URI_PREFIX}${comp.role.replace('SO:', '')}"/>`);

    if (comp.sequence) {
      lines.push(`    <sbol:hasSequence>`);
      lines.push(`      <sbol:Sequence rdf:about="${ns}/${escXml(comp.displayId)}/Sequence">`);
      lines.push(`        <sbol:displayId>${escXml(comp.displayId)}_Sequence</sbol:displayId>`);
      lines.push(`        <sbol:elements>${escXml(comp.sequence)}</sbol:elements>`);
      lines.push(`        <sbol:encoding rdf:resource="http://sbols.org/v3#iupacNucleicAcid"/>`);
      lines.push(`      </sbol:Sequence>`);
      lines.push(`    </sbol:hasSequence>`);
    }

    lines.push(`  </sbol:Component>`);
    lines.push(``);
  }

  lines.push(`</rdf:RDF>`);
  return lines.join('\n');
}

// ── Serialize to Turtle (RDF/Turtle) ──────────────────────────────────────────
function serializeToTurtle(
  doc: Omit<SBOLDocument, 'serializedXml' | 'serializedTurtle'>,
): string {
  const ns = doc.namespace;
  const lines: string[] = [
    `@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .`,
    `@prefix sbol: <http://sbols.org/v3#> .`,
    `@prefix dcterms: <http://purl.org/dc/terms/> .`,
    `@prefix prov: <http://www.w3.org/ns/prov#> .`,
    `@prefix SO: <http://identifiers.org/SO:> .`,
    `@prefix SBO: <http://identifiers.org/biomodels.sbo/> .`,
    `@prefix : <${ns}/> .`,
    ``,
    `# SBOL 3.0 Document: ${doc.name}`,
    `# Generated by Nexus-Bio Axon SBOL Serializer`,
    `# Timestamp: ${doc.createdAt}`,
    ``,
  ];

  // Top-level construct
  lines.push(`<${ns}/${doc.displayId}>`);
  lines.push(`    a sbol:Component ;`);
  lines.push(`    sbol:displayId "${doc.displayId}" ;`);
  lines.push(`    sbol:name "${doc.name}" ;`);
  lines.push(`    dcterms:description "${doc.description}" ;`);
  lines.push(`    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;`);
  lines.push(`    sbol:role SO:0000804 .`);
  lines.push(``);

  // Individual parts
  for (const comp of doc.components) {
    lines.push(`<${ns}/${comp.displayId}>`);
    lines.push(`    a sbol:Component ;`);
    lines.push(`    sbol:displayId "${comp.displayId}" ;`);
    lines.push(`    sbol:name "${comp.name}" ;`);
    lines.push(`    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;`);
    lines.push(`    sbol:role ${comp.role.replace(':', ':')} .`);
    lines.push(``);
  }

  return lines.join('\n');
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Serialize a list of genetic circuit nodes into an SBOL 3.0 document.
 *
 * @param circuitNodes - Genetic circuit nodes from the GECAIR module
 * @param constructName - Display name for the top-level construct
 * @param namespace - URI namespace (default: Nexus-Bio convention)
 * @returns Complete SBOLDocument with XML and Turtle serializations
 */
export function serializeToSBOL(
  circuitNodes: CircuitNode[],
  constructName: string,
  namespace: string = 'https://nexus-bio.org/sbol3',
): SBOLDocument {
  const allParts = circuitNodes.flatMap(n => n.parts);
  const components = partsToComponents(allParts, namespace);
  const interactions = inferInteractions(circuitNodes, namespace);
  const displayId = constructName.replace(/[^a-zA-Z0-9_]/g, '_');
  const createdAt = new Date().toISOString();

  const docBase = {
    displayId,
    name: constructName,
    description: `Genetic construct "${constructName}" with ${components.length} parts, generated by Nexus-Bio Axon.`,
    namespace,
    components,
    interactions,
    createdAt,
  };

  return {
    ...docBase,
    serializedXml: serializeToXml(docBase),
    serializedTurtle: serializeToTurtle(docBase),
  };
}

/**
 * Serialize from raw GeneticPart[] (simpler API for direct part lists).
 */
export function serializePartsToSBOL(
  parts: GeneticPart[],
  constructName: string,
  namespace: string = 'https://nexus-bio.org/sbol3',
): SBOLDocument {
  const node: CircuitNode = { id: constructName, parts };
  return serializeToSBOL([node], constructName, namespace);
}

/**
 * Validate an SBOLDocument for structural correctness.
 * Returns a list of warnings/errors.
 */
export function validateSBOL(doc: SBOLDocument): string[] {
  const issues: string[] = [];

  if (doc.components.length === 0) {
    issues.push('ERROR: Document has no components.');
  }

  for (const comp of doc.components) {
    if (!comp.displayId || comp.displayId.trim() === '') {
      issues.push(`ERROR: Component missing displayId.`);
    }
    const validRoles: string[] = ['SO:0000167', 'SO:0000139', 'SO:0000316', 'SO:0000141', 'SO:0000110', 'SO:0000296', 'SO:0000057'];
    if (!validRoles.includes(comp.role)) {
      issues.push(`WARNING: Component "${comp.displayId}" has non-standard role "${comp.role}".`);
    }
  }

  // Check construct ordering: promoter should precede RBS should precede CDS should precede terminator
  const roleOrder = ['SO:0000167', 'SO:0000139', 'SO:0000316', 'SO:0000141'];
  let lastIdx = -1;
  for (const comp of doc.components) {
    const idx = roleOrder.indexOf(comp.role);
    if (idx !== -1) {
      if (idx < lastIdx) {
        issues.push(`WARNING: Part "${comp.displayId}" (${ROLE_LABEL[comp.role]}) appears out of canonical order (P→R→C→T).`);
      }
      lastIdx = idx;
    }
  }

  if (issues.length === 0) {
    issues.push('VALID: Document passes all structural checks.');
  }

  return issues;
}

export { generateUUID };
